spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssmdemo?serverTimezone=GMT%2B8
    username: root
    password: gcy1996612
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
